name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:  
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  checks: write

jobs:
  setup-and-test:
    name: Setup Node, install & test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint (if available)
        run: |
          if npm run | grep -q "lint"; then
            npm run lint
          else
            echo "No lint script found, skipping."
          fi

      - name: Run tests
        run: |
          if npm run | grep -q "test"; then
            npm test -- --ci
          else
            echo "No test script found, skipping."
          fi

      - name: Upload test logs (artifact)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-logs
          path: |
            ./npm-debug.log
            ./test-results || true